---
  # Tarefas para instalação do SonarQube

 - name: instalar unzip e Java
   yum: name={{ item }} state=present
   with_items:
     - unzip
     - java-1.8.0-openjdk

 - name: Instalando o SonarQube
   unarchive:
    src: "{{ sonar_link }}"
    dest: "{{ sonar_dest }}"
    remote_src: True

 - name: Transferindo arquivo de Configuração do Sonar
   template: src=sonar.properties dest={{ dest_conf }}

 - name: Executando SonarQube
   shell: "{{ start_sonar }}"
